button_card_templates: !include_dir_merge_named minimalist-templates/

kiosk_mode:
  kiosk: true

views:
  - type: custom:grid-layout
    title: _home
    path: 0
    layout:
      #default
      grid-gap: 10%
      grid-template-columns: auto
      grid-template-rows: auto
      grid-template-areas: |
        ".  chips       chips         chips         chips         chips       ."
        ".  t1          t1            t1            t1            t1          ."
        ".  navigation  navigation    navigation    navigation    navigation  ."
        ".  t2          t2            t2            t2            t2          ."
        ".  persons     persons       persons       persons       persons     ."
        ".  .           .             .             .             .           ."
        ".  .           .             .             .             .           ."
        ".  .           .             .             .             .           ."
        ".  .           .             .             .             .           ."
      mediaquery:
        #phone
        "(max-width: 800px)":
          grid-gap: 10%
          grid-template-columns: auto
          grid-template-rows: auto
          grid-template-areas: |
            ".  chips       chips         chips         chips         chips       ."
            ".  t1          t1            t1            t1            t1          ."
            ".  navigation  navigation    navigation    navigation    navigation  ."
            ".  t2          t2            t2            t2            t2          ."
            ".  persons     persons       persons       persons       persons     ."
            ".  .           .             .             .             .           ."
            ".  .           .             .             .             .           ."
            ".  .           .             .             .             .           ."
            ".  .           .             .             .             .           ."
        #portrait
        "(max-width: 1200px)":
          grid-gap: 10%
          grid-template-columns: auto
          grid-template-rows: auto
          grid-template-areas: |
            ".  chips       chips         chips         chips         chips       ."
            ".  t1          t1            t1            t1            t1          ."
            ".  navigation  navigation    navigation    navigation    navigation  ."
            ".  t2          t2            t2            t2            t2          ."
            ".  persons     persons       persons       persons       persons     ."
            ".  .           .             .             .             .           ."
            ".  .           .             .             .             .           ."
            ".  .           .             .             .             .           ."
            ".  .           .             .             .             .           ."
    cards:
      - type: grid
        view_layout:
          grid-area: chips
        columns: 1
        cards:

          - type: 'custom:button-card'
            template: chip_temperature
            variables:
              ulm_chip_temperature_inside: sensor.steckdose_spulmaschine_temperature
              ulm_chip_temperature_outside: sensor.dwd_weather_kraichtal_gochsheim_temperature
              ulm_chip_temperature_weather: weather.dwd_weather_kraichtal_gochsheim

      - type: grid
        view_layout:
          grid-area: t1
        columns: 1
        cards:

          - type: custom:button-card
            template: title
            name: Zu Hause

      - type: grid
        view_layout:
          grid-area: navigation
        columns: 1
        cards:

          - type: custom:button-card
            template: card_navigate
            variables:
              ulm_card_navigate_path: /lovelace-minimalist/1
              ulm_card_navigate_title: Beleuchtung
              ulm_card_navigate_icon: mdi:lamps-outline

          - type: custom:button-card
            template: card_navigate
            variables:
              ulm_card_navigate_path: /lovelace-minimalist/2
              ulm_card_navigate_title: Geräte
              ulm_card_navigate_icon: mdi:devices

      - type: grid
        view_layout:
          grid-area: t2
        columns: 1
        cards:

          - type: custom:button-card
            template: title
            name: Anwesenheit
            label: 'Personen'

      - type: grid
        view_layout:
          grid-area: t2
        columns: 1
        cards:

          - type: custom:button-card
            template: title
            name: Anwesenheit
            label: 'Personen'

      - type: grid
        view_layout:
          grid-area: persons
        columns: 1
        cards:

          - type: 'custom:button-card'
            template: card_person
            variables:
              ulm_card_person_entity: person.simon
              ulm_card_person_use_entity_picture: false
              ulm_card_person_zone1: Simon Arbeit

          - type: 'custom:button-card'
            template: card_person
            variables:
              ulm_card_person_entity: person.lisa
              ulm_card_person_use_entity_picture: false
              ulm_card_person_zone1: Lisa Arbeit
