button_card_templates: !include button_card_templates.yaml

kiosk_mode:
  kiosk: true

views:
  - type: custom:grid-layout
    path: 0
    layout:
      #default
      grid-gap: var(--custom-layout-card-padding)
      grid-template-columns: repeat(5, 1fr) 0
      grid-template-rows: 0 repeat(2, fit-content(100%)) 0fr
      grid-template-areas: |
        "sidebar  .             .             .             .         ."
        "sidebar  daheim        wohnzimmer    wohnzimmer    buero     ."
        "sidebar  schlafzimmer  schlafzimmer  sonstiges     media     ."
        "sidebar  footer        footer        footer        footer    ."
        "sidebar  .             .             .             .         ."
      mediaquery:
        #phone
        "(max-width: 800px)":
          grid-gap: calc(var(--custom-layout-card-padding) * 1.5)
          grid-template-columns: 0 repeat(2, 1fr) 0
          grid-template-rows: 0 repeat(5, fit-content(100%)) 0fr
          grid-template-areas: |
            ".  .             .             ."
            ".  sidebar       sidebar       ."
            ".  wohnzimmer    wohnzimmer    ."
            ".  schlafzimmer  schlafzimmer  ."
            ".  buero         sonstiges     ."
            ".  media         daheim        ."
            ".  footer        footer        ."
            ".  .             .             ."
        #portrait
        "(max-width: 1200px)":
          grid-gap: var(--custom-layout-card-padding)
          grid-template-columns: repeat(3, 1fr) 0
          grid-template-rows: 0 repeat(5, fit-content(100%)) 0fr
          grid-template-areas: |
            "sidebar  .             .             ."
            "sidebar  wohnzimmer    wohnzimmer    ."
            "sidebar  schlafzimmer  schlafzimmer  ."
            "sidebar  buero         sonstiges     ."
            "sidebar  media         daheim        ."
            "sidebar  footer        footer        ."
            "sidebar  .             .             ."
    cards:

      #################################################
      #                                               #
      #                    SIDEBAR                    #
      #                                               #
      #################################################

      - type: markdown
        view_layout:
          grid-area: sidebar
        content: |
          {% set attributes = states.sensor.template_sidebar.attributes | default %}
          {% for template in attributes %}
          {{ state_attr('sensor.template_sidebar', template) }}
          {% endfor %}
        style: #force style - duplicate of themes markdown
          {.: "ha-card{background-color:#00000010;border-radius:0;min-height:100vh;animation:ha-card 1s forwards}@keyframes ha-card{0%,100%{border-right:.1vw solid rgba(58,69,73,.2)}}@media screen and (max-width:800px){ha-card{background:0 0;min-height:100%;animation:none}}\n", ha-markdown: {.: "ha-markdown{padding:var(--custom-layout-card-padding) 2vw 0 var(--custom-layout-card-padding)!important;pointer-events:none}@media screen and (max-width:800px){ha-markdown{padding:0!important}}\n", $: "p>span{font-family:SF Text;font-size:var(--markdown-sidebar-clock-font-size);font-weight:200;line-height:var(--markdown-sidebar-clock-line-height);letter-spacing:-.05vw;margin-left:-.3vw;color:var(--ha-card-header-color)}p>span>span{position:relative;top:-.09em}p{font-family:SF Display;font-size:var(--markdown-sidebar-font-size);line-height:var(--markdown-sidebar-line-height);font-weight:300;letter-spacing:.06vw;color:#6a7377}p>b{color:var(--ha-card-header-color)}@media screen and (max-width:1200px){p>span{font-size:calc(var(--markdown-sidebar-clock-font-size) * 1.4);line-height:calc(var(--markdown-sidebar-clock-line-height) * 1.4)}p{font-size:calc(var(--markdown-sidebar-font-size) * 1.4);line-height:calc(var(--markdown-sidebar-line-height) * 1.4)}}@media screen and (max-width:800px){p>span{font-size:calc(var(--markdown-sidebar-clock-font-size) * 2.6);line-height:calc(var(--markdown-sidebar-clock-line-height) * 2.6)}p{font-size:calc(var(--markdown-sidebar-font-size) * 2.6);line-height:calc(var(--markdown-sidebar-line-height) * 2.6);letter-spacing:.16vw}}\n"}}

      - type: grid
        view_layout:
          grid-area: sidebar
        cards:
          - type: button
            icon: mdi:robot-vacuum
            tap_action:
              !include popup/sidebar_vacuum.yaml

          - type: button
            icon: mdi:information-outline
            tap_action:
              !include popup/sidebar_information.yaml

          - type: button
            icon: mdi:arrow-up-bold-circle-outline
            tap_action:
              !include popup/sidebar_update.yaml

      #################################################
      #                                               #
      #               Wohn & Esszimmer                #
      #                                               #
      #################################################

      - type: grid
        title: Wohn & Esszimmer
        view_layout:
          grid-area: wohnzimmer
        columns: 4
        cards:

          - type: custom:button-card
            entity: binary_sensor.philipstv
            name: Tv
            hold_action:
              !include popup/wohnzimmer_tv.yaml
            template:
              - base
              - icon_tv

          - type: custom:button-card
            entity: fan.wohnzimmer
            name: "Ventilator"
            tap_action:
              !include popup/wohnzimmer_venti.yaml
            template:
              - base
              - icon_fan2

          - type: custom:button-card
            entity: light.wohnzimmer_deckenlampe
            name: Wohnzimmer
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.stehlampe_wohnzimmer_links
            name: Links
            template:
              - light
              - icon_shade

          - type: custom:button-card
            entity: light.wohnzimmer_stehlampe_rechts
            name: Rechts
            template:
              - light
              - icon_shade

          - type: custom:button-card
            entity: light.wohnzimmer_lightstrip
            name: Lightstrip
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.kuche_esstisch
            name: Esstisch
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.kuche_herd
            name: Herd
            template:
              - light
              - icon_hue



      #################################################
      #                                               #
      #              Schlaf- & Kinderzimmer           #
      #                                               #
      #################################################

      - type: grid
        title: Schlaf & Kinderzimmer
        view_layout:
          grid-area: schlafzimmer
        columns: 4
        cards:

          - type: custom:button-card
            entity: climate.klimaanlage
            name: Klima
            template:
              - climate

          - type: custom:button-card
            entity: light.schlafzimmer_deckenlampe
            name: Decke
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.schlafzimmer_nachttisch_lisa
            name: Lisa
            template:
              - light
              - icon_lamp

          - type: custom:button-card
            entity: light.schlafzimmer_nachttisch_simon
            name: Simon
            template:
              - light
              - icon_lamp

          - type: custom:button-card
            entity: light.kinderzimmer_deckenlampe
            name: Kinderzimmer
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.kinderzimmer_tischleuchte
            name: Wickeltisch
            template:
              - light
              - icon_lamp


      #################################################
      #                                               #
      #                      Büro                     #
      #                                               #
      #################################################

      - type: grid
        title: Büro
        view_layout:
          grid-area: buero
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.buro_deckenlampe
            name: Decke
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.buro_schreibtisch
            name: Schreibtisch
            template:
              - light
              - icon_lamp

          - type: custom:button-card
            entity: light.nahtisch
            name: Nähtisch
            template:
              - light
              - icon_spot

          - type: custom:button-card
            entity: switch.simon_pc
            name: PC
            triggers_update:
              - lock.dator
              - script.home_leave
            hold_action:
              !include popup/buero_dator.yaml
            template:
              - base
              - icon_imac
              - loader
              - lock


      #################################################
      #                                               #
      #                   Sonstiges                   #
      #                                               #
      #################################################

      - type: grid
        title: Sonstiges
        view_layout:
          grid-area: sonstiges
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.shelly_deckenlampe_bad
            name: Bad
            template:
              - light
              - icon_bathroom

          - type: custom:button-card
            entity: light.deckenlampen_flur
            name: Flur
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.eingangstuer_decke
            name: Eingang
            template:
              - light
              - icon_closet

          - type: custom:button-card
            entity: light.wandlampen_treppenhaus
            name: Treppenhaus
            template:
              - light
              - icon_spot

      #################################################
      #                                               #
      #                     MEDIA                     #
      #                                               #
      #################################################

      - type: grid
        title: Media
        view_layout:
          grid-area: media
        columns: 1
        cards:

          - type: custom:swipe-card
            start_card: 1
            parameters:
              roundLengths: true
              effect: coverflow
              speed: 650
              spaceBetween: 20
              threshold: 7
              coverflowEffect:
                rotate: 80
                depth: 300
            cards:

              - type: vertical-stack
                cards:

                  - type: conditional
                    conditions:
                      - entity: input_select.conditional_media
                        state: wohnzimmer_2
                    card:
                      type: custom:button-card
                      entity: media_player.wohnzimmer_2
                      template:
                        - conditional_media

                  - type: conditional
                    conditions:
                      - entity: input_select.conditional_media
                        state: wohnzimmer
                    card:
                      type: custom:button-card
                      entity: media_player.wohnzimmer
                      template:
                        - conditional_media

                  - type: conditional
                    conditions:
                      - entity: input_select.conditional_media
                        state: kueche
                    card:
                      type: custom:button-card
                      entity: media_player.kueche
                      template:
                        - conditional_media

                  - type: conditional
                    conditions:
                      - entity: input_select.conditional_media
                        state: schlafzimmer
                    card:
                      type: custom:button-card
                      entity: media_player.schlafzimmer
                      template:
                        - conditional_media

                  - type: conditional
                    conditions:
                      - entity: input_select.conditional_media
                        state: bad
                    card:
                      type: custom:button-card
                      entity: media_player.bad
                      template:
                        - conditional_media

                  - type: conditional
                    conditions:
                      - entity: input_select.conditional_media
                        state: buro
                    card:
                      type: custom:button-card
                      entity: media_player.buro
                      template:
                        - conditional_media


              - type: grid
                columns: 3
                cards:

                  - type: custom:button-card
                    entity: media_player.wohnzimmer_2
                    name: Chromecast
                    template:
                      - media
                      - icon_monitors

                  - type: custom:button-card
                    entity: media_player.wohnzimmer
                    name: Wohnzimmer
                    template:
                      - media
                      - icon_monitors

                  - type: custom:button-card
                    name: Küche
                    entity: media_player.kueche
                    template:
                      - media
                      - icon_monitors

                  - type: custom:button-card
                    name: Schlafzimmer
                    entity: media_player.schlafzimmer
                    template:
                      - media
                      - icon_monitors

                  - type: custom:button-card
                    name: Bad
                    entity: media_player.bad
                    template:
                      - media
                      - icon_monitors

                  - type: custom:button-card
                    name: Büro
                    entity: media_player.buro
                    template:
                      - media
                      - icon_monitors

      #################################################
      #                                               #
      #                    Daheim                     #
      #                                               #
      #################################################

      - type: grid
        title: Daheim
        view_layout:
          grid-area: daheim
        columns: 2
        cards:

          - type: custom:button-card
            entity: person.simon
            name: Simon
            tap_action:
              !include popup/daheim_simon.yaml
            hold_action:
              action: none
            template: person

          - type: custom:button-card
            entity: person.lisa
            name: Lisa
            tap_action:
              !include popup/daheim_lisa.yaml
            hold_action:
              action: none
            template: person

          - type: custom:button-card
            entity: script.home_leave
            name: Alles aus
            hold_action:
              action: none
            template:
              - base
              - icon_away

          - type: custom:button-card
            entity: script.home_arrive
            name: Wieder da
            hold_action:
              action: none
            template:
              - base
              - icon_home

      #################################################
      #                                               #
      #                    FOOTER                     #
      #                                               #
      #################################################

      - type: markdown
        view_layout:
          grid-area: footer
        content: >
          {{ state_attr('sensor.template_coronavirus', 'template') }}
        style: #force style - duplicate of themes markdown
          {.: "ha-card,ha-markdown{background:0 0;padding:0!important;pointer-events:none;margin-top:-1vw}ha-markdown{overflow:hidden}\n", ha-markdown$: "ha-markdown-element{opacity:.6;font-size:1.26vw;font-weight:400;--mdc-icon-size:1.2vw;font-family:SF Display;letter-spacing:.05vw;line-height:0;white-space:nowrap}ha-icon{vertical-align:3%;opacity:.4}@media screen and (max-width:800px){ha-markdown-element{display:none}}\n"}
